version: "3.7"
services:
  api:
    container_name: wikux-api
    image: golang:alpine
    command: sleep 30000
    volumes:
      - .:/go/src/wikux-api
    ports:
      - 0.0.0.0:10080:10080
    environment:
      IKUX_HTTP_PORT: 10080
      WIKUX_DB_HOST: 
      WIKUX_DB_USER: 
      WIKUX_DB_PASSWORD: 
      WIKUX_DB_MAXOPENCONS:
      WIKUX_DB_MAXIDLECONS:
      WIKUX_SMTP_HOST:
      WIKUX_SMTP_USER:
      WIKUX_SMTP_PASSWORD:
      GIN_MODE: debug
    links:
      - db
  db:
    container_name: wikux-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - ./sql/mysql:/docker-entrypoint-initdb.d
    ports:
      - 0.0.0.0:3306:3306
